# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='student',
        ),
        migrations.AddField(
            model_name='ninja',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Dojos', to='first_app.Dojo'),
            preserve_default=False,
        ),
    ]
