# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180222_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
