FLASK_APP='manage.py'
FLASK_ENV=development
SECRET_KEY='you-will-never-guess'
DB_HOST=localhost
DB_USERNAME='flogger_user'
DB_PASSWORD='flogger_password'
DATABASE_NAME='flogger'
MYSQL_ROOT_PASSWORD=rootpass
BLOG_NAME='The Flogger Blog'
BLOG_POST_IMAGES_PATH='C:\Users\justl\Desktop\dojo_assignments\Python\\flogger\static\images\uploads'