# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
