# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='DEFAULT NOTE', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
