# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseManager',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(),
        ),
    ]
